gibz_news_homepage:
    path:     /{page}
    defaults: { _controller: GibzNewsBundle:News:index, page: 1 }
    requirements:
        page: '\d+'

gibz_news_show:
    path:     /{slug}
    defaults: { _controller: GibzNewsBundle:News:show }
