services:
  admin.article:
    class: Gibz\NewsBundle\Admin\ArticleAdmin
    arguments: [~, Gibz\NewsBundle\Entity\Article, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, label: Article }