admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix:   /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

homepage:
    path:     /
    defaults: {_controller: "GibzNewsBundle:News:index"}

gibz_news:
    resource: "@GibzNewsBundle/Resources/config/routing.yml"
    prefix:   /news