<?php

namespace Gibz\NewsBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function getQueryForPaginator()
    {
        return $this->createQueryBuilder('articles')->from('GibzNewsBundle:Article', 'article');
    }
}
